baseURL = "https://tjmolnar.onrender.com"

# ------------------------------
languageCode = "en-us"
DefaultContentLanguage = "en"

# ------------------------------
title = "TJ Molnar [tjr3xx]"
author = "TJ Molnar"
copyright = "Copyright © 2023, tjmolnar.com"

# ------------------------------
paginate = 5
enableInlineShortcodes = true
disableKinds = ['taxonomy', 'term', 'contact']

# ------------------------------
[params]
  github = "https://github.com/tjr3xx"
  linkedin = "https://www.linkedin.com/in/tj-molnar"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
    
[outputs]
    home = ["HTML"]

