baseURL = "https://tjmolnar.onrender.com"

# ------------------------------
languageCode = "en-us"
DefaultContentLanguage = "en"

# ------------------------------
title = "TJ Molnar [tjr3xx]"
author = "TJ Molnar"
copyright = "Copyright © 2022, tjmolnar.com"

# ------------------------------
paginate = 5
enableInlineShortcodes = true

# ------------------------------
[params]
  github = "https://github.com/tjr3xx"
  linkedin = "https://www.linkedin.com/in/tj-molnar"
  
# ------------------------------
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10